version: '3.9'
networks:
  jenkins:
    driver: bridge
services:
  jenkins:
    container_name: 'jenkins-blueocean'
    build:
      context: .
    user: 'root'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home:rw
      - /usr/local/bin:/usr/hostbin
      - /usr/local/bin/docker:/bin/docker
      - /usr/local/bin/docker-compose:/bin/docker-compose
    privileged: true
    networks:
      - jenkins
